// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAWc_iFQdcwBxVe5y2gOoqeegozfzxts',
    appId: '1:767968904403:web:282bae382f21109a7c0026',
    messagingSenderId: '767968904403',
    projectId: 'weshop-d0b53',
    authDomain: 'weshop-d0b53.firebaseapp.com',
    databaseURL: 'https://weshop-d0b53-default-rtdb.firebaseio.com',
    storageBucket: 'weshop-d0b53.appspot.com',
    measurementId: 'G-P3CBR5JLC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LWLS_-2UOK2Tu_ISyOzB7wtmeFJK8QY',
    appId: '1:767968904403:android:2cb97d21bdaca1947c0026',
    messagingSenderId: '767968904403',
    projectId: 'weshop-d0b53',
    databaseURL: 'https://weshop-d0b53-default-rtdb.firebaseio.com',
    storageBucket: 'weshop-d0b53.appspot.com',
  );
}